; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Attiny3217_pymcuprog_updi]
framework = arduino
platform = atmelmegaavr
board = ATtiny3217

monitor_speed = 115200

board_build.f_cpu = 20000000L
board_fuses.BOOTEND = 0x5E
board_fuses.APPEND = 0x5F

; custom linker script for placing sprite data into APPDATA
board_build.ldscript = linker/sprites.ld

debug_build_flags = -Os -ggdb3 -g3
build_flags =
  -Os
  -DNDEBUG
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
  -fno-exceptions
  -Wl,-Map,firmware.map
  -DF_CPU=20000000L

upload_protocol = custom
upload_port = /dev/cu.usbserial* ; for MacOS
upload_speed = 230400

; for using pymcuprog, download and install it via PyPi
upload_flags =
    --tool
    uart
    --device
    $BOARD
    --uart
    $UPLOAD_PORT
    --clk
    $UPLOAD_SPEED

upload_command = pymcuprog write --erase $UPLOAD_FLAGS --filename $SOURCE

; burning fuses
; rn, the program takes up: 12,032 bytes, so BOOTEND could be twice that and still leave room for 2x sprites?
; BOOTEND should be 94 ==> 0x5E
; APPEND should be 0 ==> 0x00 (the rest of flash)
; rn, sprites take up 2342 byes ==> 2560 to be divisible by 256 ==> 0x0A

; writing fuses:
; pymcuprog write --tool uart --device attiny3217 --uart /dev/cu.usbmodem14101 --clk 230400 --memory fuses --offset 7 --literal 0x00 0x5E 
; reading fuses:
; pymcuprog read --tool uart --device attiny3217 --uart /dev/cu.usbmodem14101 --clk 230400 --memory fuses

; notes on BOOTEND vv
; https://onlinedocs.microchip.com/oxy/GUID-A2109DC3-B5FF-4E1B-BDB5-622C21D35F43-en-US-5/GUID-B4C7F32B-FEF9-4930-B092-2E702953E23E.html
; getting no program running when writing these bytes doe

; OKAY! So fuse 7 is APPEND
; Fuse 8 is BOOTEND (weird that they did it the other way around, idk)

; When BOOTEND is 0x00, the whole flash is BOOT (which is the only way I can get the program to run rn)
; When APPEND is 0x00, everything from BOOT onwards is APPCODE section

; docs say BOOT can write to APPCODE

; okay, so what needs to happen next is:
; i need to specify in the linker file where the bitmaps should go (APPCODE or APPDATA, gotta see what the disadvantages are), and that the code should go in BOOT

extra_scripts =
; compile bitmap arrays from .bmp's
  pre:bitmaps/compile_spritesheet.py
; compile eeprom_data.eep from eeprom_data.bin
  pre:eeprom/build_eeprom.py
